### ISSUE TITLE
In direction relationships throwing odd error, possible issue with subject class

### ISSUE THREAD

**Issue by robertness** [sineed/neo4j-rspec#11]
My in-direction relationship examples are failing.  For example, I have a model called WebPost that has many incoming comments.

I wrote the spec:

`require 'rails_helper'`
`describe WebPost do`
`it {is_expected.to have_many(:comments).with_direction(:in).with_origin(:web_post)}`
`end`

My model:

`class WebPost`
`include Neo4j::ActiveNode`
`...`
`has_many :in, :comments, origin: :web_posts`
`end`

The incoming model 

`class Comment`
`include Neo4j::ActiveNode`
`...`
`has_many :out, :web_posts, type: :recommends, model_class: :WebPost`
`end`

The spec example fails with the error;

> WebPost should have many WebPost with in direction with web_post origin
> Failure/Error: it {is_expected.to have_many(:comments).with_direction(:in).with_origin(:web_post)}
> expected the WebPost model to have many have_many with in direction with web_post origin
> ./spec/models/web_post_spec.rb:11:in 'block (2 levels) in <top (required)>'

The phrasing "WebPost should have many WebPost with in direction with web_post origin", is oddly redundant.  I was expected "WebPost should have many comments with in direction with web_post origin".  

I just updated to the most recent version of neo4j so the error might be mine, I'm still building my intuition about relationship syntax.

On the advice of @cheerfulstoic I tried specifically defining the subject;

`require 'rails_helper'`
`describe WebPost do`
`subject {WebPost}`
`it {is_expected.to have_many(:comments).with_direction(:in).with_origin(:web_post)}`
`end`

The error then became; 

> WebPost should have many Class with in direction with web_post origin
> Failure/Error: it {is_expected.to have_many(:comments).with_direction(:in).with_origin(:web_post)}
> NoMethodError:
> undefined method 'associations' for Class:Class
> /Users/robertness/.rvm/gems/ruby-2.2.3@neo4j/gems/neo4j-rspec-0.2.1/lib/neo4j/rspec/matchers/has_n.rb:105:in 'block (3 levels) in module:HasN'
> ./spec/models/web_post_spec.rb:12:in 'block (2 levels) in <top (required)>'

**Comment by robertness** [comment]
See conversation with @cheerfulstoic in gitter
https://gitter.im/neo4jrb/neo4j

**Comment by sineed** [comment]
Hi!

The subject of test case should be the instance of WebPost, so your initial code is correct for this part.

Can you use the plural for of webpost? E.g.

it {is_expected.to have_many(:comments).with_direction(:in).with_origin(:web_posts)

**Comment by sineed** [comment]
Regarding to the description of spec I will look at it in a couple of days

**Comment by cheerfulstoic** [comment]
I haven't used `have_many`/`have_one` yet, but for the other expectations I think I have `subject { ModelClass }`, so perhaps we should make the subject consistent?

**Comment by robertness** [comment]
Not sure if this helps, but figured I'd share.  Before trying this package, I had a solution for a custom matcher for relationships in place that relied on FactoryGirl.  Not sure if this is true, but I believed at the time a subject and object had to be saved in the db before a relationship could be drawn between them.  So I used used FactoryGirl to design template objects and had the matcher create instances of the templates and attempt to create a relationship between them.  Here is what I had for incoming relationships (This code was used with an older version of neo4jrb, so some of the methods might have changed in the newer version)

`module ValidateRelationship`
`RSpec::Matchers.define :have_one_incoming do |obj_name|`
`match do |sbj|`
`sbj = FactoryGirl::create(sbj.class.name.underscore.to_sym)`
`obj = FactoryGirl::create(obj_name)`
`obj_class = obj.class.name`
`sbj[obj_name] = obj`
`classes_of_incoming = sbj.rels.map {|rel| rel.start_node.class.name}`
`expect(classes_of_incoming).to include(obj_class)`
`end`
`end`
`RSpec::Matchers.define :have_many_incoming do |obj_name|`
`match do |sbj|`
`sbj = FactoryGirl::create(sbj.class.name.underscore.to_sym)`
`expect(sbj[obj_name].association.type.to_s).to eq("has_many")`
`expect(sbj[obj_name].association.direction.to_s).to eq("in")`
`obj_name_singular = obj_name.to_s.singularize.to_sym`
`obj1 = FactoryGirl::create(obj_name_singular)`
`obj2 = FactoryGirl::create(obj_name_singular)`
`sbj[obj_name] << obj1`
`sbj[obj_name] << obj2`
`nodes = {parent1: obj1, parent2: obj2, child: sbj}`
`parent_edges = nodes[:child].rels(dir: :incoming).select{|r| r.start_node.class == obj1.class}`
`expect(parent_edges[0].start_node).to eq(nodes[:parent1])`
`expect(parent_edges[1].start_node).to eq(nodes[:parent2])`
`end`
`end`
`end`

**Comment by cheerfulstoic** [comment]
It should be possible to examine that the association is defined with the property settings via reflection on the class without needing to go to the DB.  I believe that's what the gem is doing, but there might just be a small issue.

**Comment by robertness** [comment]
Hi @sineed, you are right that I should make the origin plural.  I still get the error though:

> WebPost should have many Class with in direction with web_posts origin
>       Failure/Error: it {is_expected.to have_many(:comments).with_direction(:in).with_origin(:web_posts)}
> 
> ```
>   NoMethodError:
>     undefined method `associations' for Class:Class
>   # /Users/robertness/.rvm/gems/ruby-2.2.3@neo4j/gems/neo4j-rspec-0.2.1/lib/neo4j/rspec/matchers/has_n.rb:105:in `block (3 levels) in <module:HasN>'
>   # ./spec/models/web_post_spec.rb:12:in `block (2 levels) in <top (required)>'
> ```

**Comment by sineed** [comment]
I think that the error happens because of `subject { WebPost }`, if you remove this line it should work.

@cheerfulstoic I think to be similar to `shoulda-matchers` the subject must be an instance not a class.

**Comment by cheerfulstoic** [comment]
Ah, interesting.  I wonder if that's because `describe ModelClass do` will make `ModelClass.new` the subject.  It would make sense to me to just test at the class level because there's no need for an instance, but if that's what `shouda-matchers` does then we should probably copy them

**Comment by sineed** [comment]
@robertness have you tried to use the instance of class as a subject of your test?

**Comment by robertness** [comment]
@sineed Tried that.   Check out your unit tests https://github.com/sineed/neo4j-rspec/blob/master/spec/unit/has_n_spec.rb

You lack a "has_one" case matched with an "in" direction.  I bet if you add a case for that you can replicate my error

**Comment by sineed** [comment]
Tried to reproduce error in [this](https://github.com/sineed/neo4j-rspec/tree/has_one_with_in_direction) branch but had no luck. Can you try to reproduce the error in this branch?
