### ISSUE TITLE
rake -T failing with neo4j-rspec

### ISSUE THREAD

**Issue by ernestoe** [sineed/neo4j-rspec#15]
I reproduce the problem by creating a brand new project:

```
rails new neo4j-rspec-sample -m http://neo4jrb.io/neo4j/neo4j.rb -O
```

rake -T produces the expected output:

```
rake about                                   # List versions of all Rails frameworks and the enviro...
rake assets:clean[keep]                      # Remove old compiled assets
...
```

if I now include neo4j-rspec in Gemfile, rake -T produces the following:

```
rake aborted!
NameError: uninitialized constant RSpec
/Users/ernestoe/.rvm/gems/ruby-2.3.1/gems/neo4j-rspec-0.2.3/lib/neo4j/rspec/matchers/has_n.rb:96:in `<module:HasN>'
/Users/ernestoe/.rvm/gems/ruby-2.3.1/gems/neo4j-rspec-0.2.3/lib/neo4j/rspec/matchers/has_n.rb:4:in `<module:Matchers>'
...
```

Refer to sample repository: 
https://github.com/ernestoe/neo4j-rspec-sample

**Comment by sineed** [comment]
Thanks for pointing that! This happened because you haven't configured RSpec test suite. You can avoid this bug now adding `require: false` option in `Gemfile`:

``` ruby
gem 'neo4j-rspec', require: false
```

**Comment by jmalvinchin** [comment]
Is there a more permanent fix to this already?
